# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClockWidgetExtension' do
  use_frameworks!
  platform :ios, '16.2'
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'HandyJSON'

  # Pods for ClockWidgetExtension

end

target 'SmallWidget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '16.2'
  
  
  pod 'HandyJSON'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Kingfisher'
  
  # Pods for SmallWidget

  target 'SmallWidgetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmallWidgetUITests' do
    # Pods for testing
  end

end

target 'SmallWidgetIntents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '16.2'
  pod 'HandyJSON'

end


post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          end
      end

      installer.generated_projects.each do |project|
        project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.2'
          end
        end
      end
end

